spring.application.name=tinyurl
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=<render_db_url>
spring.datasource.username=<username>
spring.datasource.password=<password>
